=begin
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
=end

def sum_even_fib(n, max_n)
    dp = [1, 2]
    sum = 0

    for i in 2..n-1
        dp[i] = dp[i - 2] + dp[i - 1]
        if dp[i] < max_n and dp[i] % 2 != 0
            sum += dp[i]
        end
    end
    return sum + dp[1]
end

puts sum_even_fib(40, 4000000) #46137312
